"""Core service protocols (interfaces) for Mycelos.

Every core component is designed as Protocol + Implementation.
The Protocol defines the contract; implementations can be swapped
without changing the rest of the system.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from mycelos.agents.models import AgentInput, AgentOutput


@runtime_checkable
class StorageBackend(Protocol):
    """Interface for structured data storage."""

    def execute(self, sql: str, params: tuple = ()) -> Any: ...
    def fetchone(self, sql: str, params: tuple = ()) -> dict | None: ...
    def fetchall(self, sql: str, params: tuple = ()) -> list[dict]: ...
    def executescript(self, sql: str) -> None: ...


@runtime_checkable
class MemoryService(Protocol):
    """Interface for agent memory management."""

    def get(self, user_id: str, scope: str, key: str, agent_id: str | None = None) -> Any: ...
    def set(self, user_id: str, scope: str, key: str, value: Any, agent_id: str | None = None, created_by: str = "system") -> None: ...
    def search(self, user_id: str, scope: str, query: str, agent_id: str | None = None) -> list[dict]: ...
    def delete(self, user_id: str, scope: str, key: str, agent_id: str | None = None) -> bool: ...


@runtime_checkable
class LLMBroker(Protocol):
    """Interface for LLM access and conversation management."""

    def complete(self, messages: list[dict], model: str | None = None, tools: list[dict] | None = None, stream: bool = False) -> Any: ...
    def count_tokens(self, messages: list[dict], model: str | None = None) -> int: ...


@runtime_checkable
class SandboxManager(Protocol):
    """Interface for isolated agent execution."""

    def create(self, config: Any) -> str: ...
    def execute(self, sandbox_id: str, command: list[str], config: Any) -> Any: ...
    def cleanup(self, sandbox_id: str) -> None: ...
    def get_output_dir(self, sandbox_id: str) -> Any: ...


@runtime_checkable
class AuditLogger(Protocol):
    """Interface for audit event logging."""

    def log(self, event_type: str, agent_id: str | None = None, task_id: str | None = None, details: dict | None = None) -> None: ...
    def query(self, event_type: str | None = None, agent_id: str | None = None, limit: int = 100) -> list[dict]: ...


@runtime_checkable
class CredentialProxy(Protocol):
    """Interface for credential management."""

    def get_credential(self, service: str) -> dict | None: ...
    def store_credential(self, service: str, credential: dict) -> None: ...
    def delete_credential(self, service: str) -> None: ...
    def list_services(self) -> list[str]: ...


@dataclass(frozen=True)
class ValidationResult:
    """Result of a capability token validation."""

    valid: bool
    agent_id: str = ""
    reason: str = ""


@runtime_checkable
class PolicyEngine(Protocol):
    """Interface for policy evaluation."""

    def evaluate(self, user_id: str, agent_id: str, resource: str) -> str: ...
    def set_policy(self, user_id: str, agent_id: str | None, resource: str, decision: str, requested_by: str | None = None) -> None: ...
    def list_policies(self, user_id: str, agent_id: str | None = None) -> list[dict]: ...


@runtime_checkable
class CapabilityTokenManager(Protocol):
    """Interface for capability token management."""

    def issue(self, agent_id: str, scope: list[str], ttl_seconds: int, task_id: str | None = None, user_id: str = "default", max_requests: int | None = None) -> str: ...
    def validate(self, token_id: str, operation: str) -> ValidationResult: ...
    def revoke(self, token_id: str) -> None: ...
    def revoke_all_for_agent(self, agent_id: str) -> None: ...


@runtime_checkable
class Agent(Protocol):
    """Runtime contract for all agents in the system."""

    @property
    def agent_id(self) -> str: ...

    @property
    def agent_type(self) -> str: ...

    @property
    def capabilities_required(self) -> list[str]: ...

    def execute(self, input: AgentInput) -> AgentOutput: ...

    def validate_output(self, output: AgentOutput) -> bool: ...


@runtime_checkable
class BackgroundTaskRunnerProtocol(Protocol):
    """Interface for background task dispatch, lifecycle, and notification tracking."""

    def dispatch(self, task_type: str, payload: dict, **kwargs) -> str: ...
    def get_status(self, task_id: str) -> dict: ...
    def get_tasks_for_user(self, user_id: str, status: str | None = None) -> list[dict]: ...
    def get_completed_unnotified(self, user_id: str) -> list[dict]: ...
    def mark_notified(self, task_id: str) -> None: ...
    def cancel(self, task_id: str) -> bool: ...
    def approve_waiting(self, task_id: str) -> bool: ...
    def start_task(self, task_id: str, total_steps: int) -> None: ...
    def update_step(self, task_id: str, step_name: str, status: str, cost: float = 0) -> None: ...
    def complete_task(self, task_id: str, result: dict | None = None, error: str | None = None) -> None: ...
    def fail_task(self, task_id: str, error: str) -> None: ...


@runtime_checkable
class KnowledgeBaseProtocol(Protocol):
    """Interface for the knowledge base service."""

    def write(self, title: str, content: str, type: str = "note",
              tags: list[str] | None = None, status: str = "active",
              due: str | None = None, links: list[str] | None = None,
              priority: int = 0) -> str: ...
    def read(self, path: str) -> dict | None: ...
    def search(self, query: str, type: str | None = None,
               tags: list[str] | None = None, limit: int = 10) -> list[dict]: ...
    def list_notes(self, type: str | None = None, status: str | None = None,
                   tags: list[str] | None = None, due: str | None = None,
                   limit: int = 20) -> list[dict]: ...
    def update(self, path: str, status: str | None = None,
               tags: list[str] | None = None, due: str | None = None,
               content: str | None = None, append: bool = False,
               priority: int | None = None) -> bool: ...
    def link(self, from_path: str, to_path: str) -> bool: ...
    def find_relevant(self, text: str, top_k: int = 5,
                      threshold: float = 0.7) -> list[dict]: ...


@runtime_checkable
class SecurityProxyProtocol(Protocol):
    """Interface for the SecurityProxy — the sole gateway to external network, MCP, and LLM."""

    def http_get(self, url: str, headers: dict | None = None,
                 credential: str | None = None, timeout: int = 30,
                 user_id: str = "default", agent_id: str | None = None) -> dict: ...
    def http_post(self, url: str, body: Any = None,
                  headers: dict | None = None, credential: str | None = None,
                  timeout: int = 30, user_id: str = "default",
                  agent_id: str | None = None) -> dict: ...
    def mcp_start(self, connector_id: str, command: list[str],
                  env_vars: dict, transport: str = "stdio",
                  user_id: str = "default") -> dict: ...
    def mcp_call(self, session_id: str, tool: str, arguments: dict,
                 user_id: str = "default", agent_id: str | None = None) -> dict: ...
    def mcp_stop(self, session_id: str) -> None: ...
    def llm_complete(self, model: str, messages: list[dict],
                     tools: list[dict] | None = None, stream: bool = False,
                     user_id: str = "default", agent_id: str | None = None,
                     purpose: str = "chat") -> Any: ...
    def stt_transcribe(self, audio: bytes, filename: str = "audio.ogg",
                       language: str = "auto", model: str = "whisper-1",
                       user_id: str = "default",
                       provider: str | None = None) -> dict: ...
    def health(self) -> dict: ...
