#Requires -Version 5.1
<#
.SYNOPSIS
  Mycelos installer (Windows / PowerShell).
.PARAMETER DryRun
  Skip 'docker compose up'; just create files.
.PARAMETER DataDir
  Persistent volume path (default .\data).
#>
param(
    [switch]$DryRun,
    [string]$DataDir = ".\data"
)

$ErrorActionPreference = "Stop"
function Write-Log($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Err($msg) { Write-Host "!!! $msg" -ForegroundColor Red }

function New-Token {
    # 32 random bytes → URL-safe base64, ≈ 43 chars
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_')
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Err "Docker Desktop not found. See https://docs.docker.com/desktop/install/windows-install/"
        exit 2
    }
    docker compose version *> $null
    if ($LASTEXITCODE -ne 0) { Write-Err "Docker Compose v2 required"; exit 2 }
}

function Initialize-DataDir {
    if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir | Out-Null }
    $keyPath = Join-Path $DataDir ".master_key"
    if (-not (Test-Path $keyPath)) {
        New-Token | Set-Content -Path $keyPath -NoNewline -Encoding ASCII
        Write-Log "🔑 .master_key generated in $DataDir"
    } else {
        Write-Log "🔑 .master_key preserved"
    }
    $dbPath = Join-Path $DataDir "mycelos.db"
    if (-not (Test-Path $dbPath)) { New-Item -ItemType File -Path $dbPath | Out-Null }
}

function Initialize-EnvFile {
    if (Test-Path ".env") {
        Write-Log "🔐 .env preserved (MYCELOS_PROXY_TOKEN kept stable)"
        return
    }
    $token = New-Token
    @"
# Generated by scripts/install.ps1 on $([DateTime]::UtcNow.ToString("o"))
MYCELOS_PROXY_TOKEN=$token
MYCELOS_DATA_DIR=$DataDir
MYCELOS_PORT=9100
"@ | Set-Content -Path ".env" -Encoding UTF8
    Write-Log "🔐 .env written with fresh MYCELOS_PROXY_TOKEN"
}

function Initialize-Compose {
    $src = "https://raw.githubusercontent.com/mycelos-ai/mycelos/main/docker-compose.yml"
    $tmp = [System.IO.Path]::GetTempFileName()
    try {
        Invoke-WebRequest -Uri $src -OutFile $tmp -UseBasicParsing

        if (-not (Test-Path "docker-compose.yml")) {
            Move-Item -Path $tmp -Destination "docker-compose.yml"
            Write-Log "📦 docker-compose.yml installed"
            return
        }

        $a = Get-FileHash "docker-compose.yml" -Algorithm SHA256
        $b = Get-FileHash $tmp -Algorithm SHA256
        if ($a.Hash -eq $b.Hash) {
            Write-Log "📦 docker-compose.yml up to date"
            return
        }

        $stamp = [DateTime]::UtcNow.ToString("yyyyMMddTHHmmssZ")
        $backup = "docker-compose.yml.bak.$stamp"
        Copy-Item "docker-compose.yml" $backup
        Move-Item -Path $tmp -Destination "docker-compose.yml" -Force
        Write-Log "📦 docker-compose.yml updated (previous saved as $backup)"
    }
    finally {
        if (Test-Path $tmp) { Remove-Item -Path $tmp -ErrorAction SilentlyContinue }
    }
}

function Start-Stack {
    if ($DryRun) { Write-Log "Dry run: skipping docker compose pull/up"; return }
    Write-Log "⬆️  Pulling latest image..."
    docker compose pull
    Write-Log "🚀 Starting containers..."
    docker compose up -d
    Write-Log "⏳ Waiting for gateway to become healthy (up to 60s)..."
    $deadline = [DateTime]::UtcNow.AddSeconds(60)
    while ([DateTime]::UtcNow -lt $deadline) {
        try {
            $r = Invoke-WebRequest -Uri "http://localhost:9100/api/health" -UseBasicParsing -TimeoutSec 2
            if ($r.StatusCode -eq 200) {
                Write-Log "✅ Mycelos is running — open http://localhost:9100"
                return
            }
        } catch { }
        Start-Sleep -Seconds 2
    }
    Write-Err "Gateway did not become healthy in 60s. Check 'docker compose logs'."
    exit 3
}

Assert-Docker
Initialize-DataDir
Initialize-EnvFile
Initialize-Compose
Start-Stack
