#!/usr/bin/env bash
# Mycelos installer — zero-question bootstrap for the two-container deployment.
#
# Flags:
#   --dry-run       Skip `docker compose up`; just create files.
#   --data-dir DIR  Persistent volume path (default ./data).
#
# Exit codes:
#   0  success
#   2  prerequisite missing
#   3  stack did not become healthy within 60s

set -euo pipefail

DRY_RUN=0
DATA_DIR="./data"
COMPOSE_SRC="${MYCELOS_COMPOSE_SRC:-https://raw.githubusercontent.com/mycelos-ai/mycelos/main/docker-compose.yml}"

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --data-dir) DATA_DIR="$2"; shift ;;
        -h|--help)
            sed -n '2,10p' "$0"
            exit 0 ;;
        *) echo "Unknown flag: $1" >&2; exit 2 ;;
    esac
    shift
done

log() { echo "==> $*"; }
err() { echo "!!! $*" >&2; }

check_prereqs() {
    command -v docker >/dev/null 2>&1 \
        || { err "Docker not found. Install from https://docs.docker.com/get-docker/"; exit 2; }
    docker compose version >/dev/null 2>&1 \
        || { err "Docker Compose v2 required ('docker compose', not 'docker-compose')"; exit 2; }
    # curl is only required for remote fetches
    if [ ! -f "$COMPOSE_SRC" ]; then
        command -v curl >/dev/null 2>&1 || { err "curl not found"; exit 2; }
    fi
    command -v python3 >/dev/null 2>&1 || command -v openssl >/dev/null 2>&1 \
        || { err "Need python3 or openssl to generate tokens"; exit 2; }
}

gen_token() {
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
    else
        openssl rand -base64 48 | tr -d '\n' | head -c 43
    fi
}

ensure_data_dir() {
    mkdir -p "$DATA_DIR"
    if [ ! -f "$DATA_DIR/.master_key" ]; then
        gen_token > "$DATA_DIR/.master_key"
        chmod 600 "$DATA_DIR/.master_key"
        log "🔑 .master_key generated in $DATA_DIR"
    else
        log "🔑 .master_key preserved"
    fi
    # Pre-create the DB file so the proxy's read-only bind-mount has a target.
    # Mycelos auto-initializes the schema on first gateway start.
    touch "$DATA_DIR/mycelos.db"
}

ensure_env() {
    if [ -f .env ]; then
        log "🔐 .env preserved (MYCELOS_PROXY_TOKEN kept stable)"
        return
    fi
    local token
    token="$(gen_token)"
    cat > .env <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MYCELOS_PROXY_TOKEN="$token"
MYCELOS_DATA_DIR="$DATA_DIR"
MYCELOS_PORT=9100
EOF
    chmod 600 .env
    log "🔐 .env written with fresh MYCELOS_PROXY_TOKEN"
}

ensure_compose() {
    local new=".docker-compose.yml.new.$$"
    trap 'rm -f "$new"' RETURN
    if [ -f "$COMPOSE_SRC" ]; then
        cp "$COMPOSE_SRC" "$new"
    else
        curl -fsSL "$COMPOSE_SRC" -o "$new"
    fi

    if [ ! -f docker-compose.yml ]; then
        mv "$new" docker-compose.yml
        log "📦 docker-compose.yml installed"
        return
    fi

    if cmp -s "$new" docker-compose.yml; then
        log "📦 docker-compose.yml up to date"
        return
    fi

    local backup="docker-compose.yml.bak.$(date -u +%Y%m%dT%H%M%SZ)"
    cp docker-compose.yml "$backup"
    mv "$new" docker-compose.yml
    log "📦 docker-compose.yml updated (previous saved as $backup)"
}

install_cli_shortcut() {
    # Drop a small wrapper into ~/.local/bin so `mycelos <cmd>` works from
    # any shell (not just interactive ones where aliases would apply).
    # Points at THIS install's docker-compose.yml so multi-install users
    # don't accidentally target the wrong stack.
    local bin_dir="${HOME}/.local/bin"
    local wrapper="${bin_dir}/mycelos"
    local compose_path
    compose_path="$(pwd)/docker-compose.yml"

    mkdir -p "$bin_dir"

    cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Mycelos CLI shortcut — installed by scripts/install.sh
# Targets the stack at: $compose_path
exec docker compose -f "$compose_path" exec gateway mycelos "\$@"
EOF
    chmod +x "$wrapper"

    # Warn once if ~/.local/bin is not on PATH — tell the user how to fix it.
    case ":$PATH:" in
        *":$bin_dir:"*) log "🔧 CLI shortcut: $wrapper" ;;
        *)
            log "🔧 CLI shortcut installed: $wrapper"
            log "   (Add ~/.local/bin to your PATH to use 'mycelos <cmd>' directly,"
            log "    or call it with its full path.)"
            ;;
    esac
}

bring_up() {
    [ "$DRY_RUN" = 1 ] && { log "Dry run: skipping docker compose pull/up"; return; }

    log "⬆️  Pulling latest image..."
    docker compose pull

    log "🚀 Starting containers..."
    docker compose up -d

    log "⏳ Waiting for gateway to become healthy (up to 60s)..."
    local deadline=$(( $(date +%s) + 60 ))
    local port
    port="$(grep '^MYCELOS_PORT=' .env | cut -d= -f2)"
    port="${port:-9100}"
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if curl -fsSL "http://localhost:${port}/api/health" >/dev/null 2>&1; then
            log "✅ Mycelos is running — open http://localhost:${port}"
            return
        fi
        sleep 2
    done
    err "Gateway did not become healthy within 60s. Check 'docker compose logs'."
    exit 3
}

check_prereqs
ensure_data_dir
ensure_env
ensure_compose
install_cli_shortcut
bring_up
