#!/usr/bin/env bash
# Mycelos installer — zero-question bootstrap for the two-container deployment.
#
# Flags:
#   --dry-run       Skip `docker compose up`; just create files.
#   --data-dir DIR  Persistent volume path (default ./data).
#
# Exit codes:
#   0  success
#   2  prerequisite missing
#   3  stack did not become healthy within 60s

set -euo pipefail

DRY_RUN=0
DATA_DIR="./data"
COMPOSE_SRC="${MYCELOS_COMPOSE_SRC:-https://raw.githubusercontent.com/mycelos-ai/mycelos/main/docker-compose.yml}"

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --data-dir) DATA_DIR="$2"; shift ;;
        -h|--help)
            sed -n '2,10p' "$0"
            exit 0 ;;
        *) echo "Unknown flag: $1" >&2; exit 2 ;;
    esac
    shift
done

log() { echo "==> $*"; }
err() { echo "!!! $*" >&2; }

check_prereqs() {
    command -v docker >/dev/null 2>&1 \
        || { err "Docker not found. Install from https://docs.docker.com/get-docker/"; exit 2; }
    docker compose version >/dev/null 2>&1 \
        || { err "Docker Compose v2 required ('docker compose', not 'docker-compose')"; exit 2; }
    # curl is only required for remote fetches
    if [ ! -f "$COMPOSE_SRC" ]; then
        command -v curl >/dev/null 2>&1 || { err "curl not found"; exit 2; }
    fi
    command -v python3 >/dev/null 2>&1 || command -v openssl >/dev/null 2>&1 \
        || { err "Need python3 or openssl to generate tokens"; exit 2; }
}

gen_token() {
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
    else
        openssl rand -base64 48 | tr -d '\n' | head -c 43
    fi
}

ensure_data_dir() {
    mkdir -p "$DATA_DIR"
    if [ ! -f "$DATA_DIR/.master_key" ]; then
        gen_token > "$DATA_DIR/.master_key"
        chmod 600 "$DATA_DIR/.master_key"
        log "🔑 .master_key generated in $DATA_DIR"
    else
        log "🔑 .master_key preserved"
    fi
    # Pre-create the DB file so the proxy's read-only bind-mount has a target.
    # Mycelos auto-initializes the schema on first gateway start.
    touch "$DATA_DIR/mycelos.db"
}

ensure_env() {
    if [ -f .env ]; then
        log "🔐 .env preserved (MYCELOS_PROXY_TOKEN kept stable)"
        return
    fi
    local token
    token="$(gen_token)"
    cat > .env <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MYCELOS_PROXY_TOKEN="$token"
MYCELOS_DATA_DIR="$DATA_DIR"
MYCELOS_PORT=9100
EOF
    chmod 600 .env
    log "🔐 .env written with fresh MYCELOS_PROXY_TOKEN"
}

ensure_compose() {
    local new=".docker-compose.yml.new.$$"
    trap 'rm -f "$new"' RETURN
    if [ -f "$COMPOSE_SRC" ]; then
        cp "$COMPOSE_SRC" "$new"
    else
        curl -fsSL "$COMPOSE_SRC" -o "$new"
    fi

    if [ ! -f docker-compose.yml ]; then
        mv "$new" docker-compose.yml
        log "📦 docker-compose.yml installed"
        return
    fi

    if cmp -s "$new" docker-compose.yml; then
        log "📦 docker-compose.yml up to date"
        return
    fi

    local backup="docker-compose.yml.bak.$(date -u +%Y%m%dT%H%M%SZ)"
    cp docker-compose.yml "$backup"
    mv "$new" docker-compose.yml
    log "📦 docker-compose.yml updated (previous saved as $backup)"
}

install_cli_shortcut() {
    # Drop a small wrapper into ~/.local/bin so `mycelos <cmd>` works from
    # any shell (not just interactive ones where aliases would apply).
    # Points at THIS install's docker-compose.yml so multi-install users
    # don't accidentally target the wrong stack.
    local bin_dir="${HOME}/.local/bin"
    local wrapper="${bin_dir}/mycelos"
    local compose_path
    compose_path="$(pwd)/docker-compose.yml"

    mkdir -p "$bin_dir"

    cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Mycelos CLI shortcut — installed by scripts/install.sh
# Targets the stack at: $compose_path
#
# Most subcommands are forwarded to the in-container CLI. A handful
# of "stack-level" actions must run on the HOST (docker itself cannot
# pull or restart its own running container), so they short-circuit
# the forward and run here directly.
set -e

MYCELOS_COMPOSE="$compose_path"

case "\$1" in
    update)
        shift
        cd "\$(dirname "\$MYCELOS_COMPOSE")"
        docker compose -f "\$MYCELOS_COMPOSE" pull
        exec docker compose -f "\$MYCELOS_COMPOSE" up -d "\$@"
        ;;
    restart)
        shift
        exec docker compose -f "\$MYCELOS_COMPOSE" restart "\$@"
        ;;
    logs)
        shift
        exec docker compose -f "\$MYCELOS_COMPOSE" logs "\$@"
        ;;
    shell)
        exec docker compose -f "\$MYCELOS_COMPOSE" exec gateway bash
        ;;
    stop)
        # Docker-level stop overrides the old in-container 'mycelos stop'
        # which was a single-container-era command; in the two-container
        # world 'stop' means 'stop the stack'.
        exec docker compose -f "\$MYCELOS_COMPOSE" stop
        ;;
    *)
        exec docker compose -f "\$MYCELOS_COMPOSE" exec gateway mycelos "\$@"
        ;;
esac
EOF
    chmod +x "$wrapper"

    # Warn once if ~/.local/bin is not on PATH — tell the user how to fix it.
    case ":$PATH:" in
        *":$bin_dir:"*) log "🔧 CLI shortcut: $wrapper" ;;
        *)
            log "🔧 CLI shortcut installed: $wrapper"
            log "   (Add ~/.local/bin to your PATH to use 'mycelos <cmd>' directly,"
            log "    or call it with its full path.)"
            ;;
    esac
}

install_cli_completion() {
    # Static tab-completion for the wrapper. We introspect the Click
    # command tree ONCE in the running gateway container, then write
    # hand-rolled shell completions that need no docker-exec at tab
    # press. Dynamic values (agent names, connector IDs, session UUIDs)
    # are deliberately NOT completed — the command tree is what actually
    # benefits from tab-completion; values users usually know already.
    #
    # Refresh cadence: a re-run of install.sh (which you do to update
    # the Docker image anyway) picks up any new commands the new image
    # ships.
    [ "$DRY_RUN" = 1 ] && return 0

    local bin_dir="${HOME}/.local/bin"
    local wrapper="${bin_dir}/mycelos"
    [ -x "$wrapper" ] || return 0

    log "⇥  Extracting CLI command tree from the gateway container..."
    local tree
    tree="$(docker compose exec -T gateway python - <<'PY'
import json
from mycelos.cli.main import cli

def walk(cmd):
    node = {"subcommands": {}, "options": []}
    for p in cmd.params:
        for o in getattr(p, "opts", []) or []:
            if o.startswith("--"):
                node["options"].append(o)
    if hasattr(cmd, "commands"):
        for name, sub in cmd.commands.items():
            node["subcommands"][name] = walk(sub)
    return node

print(json.dumps(walk(cli)))
PY
    )" 2>/dev/null
    if [ -z "$tree" ]; then
        log "   (failed to extract — skipping completion install)"
        return 0
    fi

    # Render completion scripts from the JSON tree via an inlined
    # Python script on the host (no network, no extra deps).
    local bash_target="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/mycelos"
    local zsh_dir="${HOME}/.local/share/zsh/site-functions"
    local zsh_target="${zsh_dir}/_mycelos"
    local fish_target="${HOME}/.config/fish/completions/mycelos.fish"
    mkdir -p "$(dirname "$bash_target")" "$zsh_dir" "$(dirname "$fish_target")" 2>/dev/null

    MYCELOS_TREE_JSON="$tree" \
    MYCELOS_BASH_OUT="$bash_target" \
    MYCELOS_ZSH_OUT="$zsh_target" \
    MYCELOS_FISH_OUT="$fish_target" \
    python3 - <<'PY'
import json, os
tree = json.loads(os.environ["MYCELOS_TREE_JSON"])

# Host-side shortcuts the wrapper intercepts before forwarding to the
# container. Merged into the Click-derived tree so tab-completion sees
# them as regular top-level commands. 'stop' already exists in Click
# and is deliberately reused — the wrapper overrides its behavior.
HOST_SHORTCUTS = {
    "update":  {"subcommands": {}, "options": []},
    "restart": {"subcommands": {"gateway": {"subcommands": {}, "options": []},
                                "proxy":   {"subcommands": {}, "options": []}},
                "options": []},
    "logs":    {"subcommands": {"gateway": {"subcommands": {}, "options": []},
                                "proxy":   {"subcommands": {}, "options": []}},
                "options": ["--follow", "--tail"]},
    "shell":   {"subcommands": {}, "options": []},
}
for name, node in HOST_SHORTCUTS.items():
    tree["subcommands"].setdefault(name, node)

def cmds_at(path):
    node = tree
    for p in path:
        node = node["subcommands"].get(p)
        if node is None:
            return [], []
    return sorted(node["subcommands"].keys()), sorted(set(node["options"]))

# Collect all paths depth-first for switch statements
def walk(node, path=()):
    yield path, node
    for name, sub in node["subcommands"].items():
        yield from walk(sub, path + (name,))

# --- bash ---
# Case on the joined subcommand path; each branch emits the valid tokens.
bash_branches = []
for path, node in walk(tree):
    tokens = sorted(set(list(node["subcommands"].keys()) + list(node["options"])))
    key = " ".join(path) if path else ""
    bash_branches.append(f'        "{key}") words="{" ".join(tokens)}" ;;')

bash_script = """# Mycelos CLI tab-completion (static — refreshed by scripts/install.sh)
_mycelos_complete() {
    local cur prev words cword
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    # Build the subcommand path: every word after "mycelos" that does
    # not start with a dash, stopping when we hit the current cursor.
    local path=""
    local i
    for (( i=1; i<COMP_CWORD; i++ )); do
        local w="${COMP_WORDS[i]}"
        [[ "$w" == -* ]] && continue
        [[ -z "$path" ]] && path="$w" || path="$path $w"
    done

    local words=""
    case "$path" in
""" + "\n".join(bash_branches) + """
    esac

    COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}
complete -F _mycelos_complete mycelos
"""
with open(os.environ["MYCELOS_BASH_OUT"], "w") as f:
    f.write(bash_script)

# --- zsh ---
# Same strategy, but use _arguments / compadd.
zsh_branches = []
for path, node in walk(tree):
    tokens = sorted(set(list(node["subcommands"].keys()) + list(node["options"])))
    key = " ".join(path) if path else ""
    # Quote each token for zsh.
    quoted = " ".join(f"'{t}'" for t in tokens)
    zsh_branches.append(f'        "{key}") _values "token" {quoted} ;;')

zsh_script = """#compdef mycelos
# Mycelos CLI tab-completion (static — refreshed by scripts/install.sh)

_mycelos_complete() {
    local path=""
    local i
    for (( i=2; i<=CURRENT-1; i++ )); do
        local w="${words[i]}"
        [[ "$w" == -* ]] && continue
        [[ -z "$path" ]] && path="$w" || path="$path $w"
    done

    case "$path" in
""" + "\n".join(zsh_branches) + """
    esac
}
_mycelos_complete "$@"
"""
with open(os.environ["MYCELOS_ZSH_OUT"], "w") as f:
    f.write(zsh_script)

# --- fish ---
# fish uses per-command "complete -c" lines. Emit one line per
# (parent-path, child-token) pair with a -n gating condition.
def path_cond(path):
    if not path:
        return '__fish_use_subcommand'
    # expects every earlier token in sequence
    return " ; and ".join([f"__fish_seen_subcommand_from {p}" for p in path])

fish_lines = ["# Mycelos CLI tab-completion (static — refreshed by scripts/install.sh)"]
for path, node in walk(tree):
    cond = path_cond(path)
    for sub in sorted(node["subcommands"].keys()):
        fish_lines.append(f"complete -c mycelos -n '{cond}' -f -a '{sub}'")
    for opt in sorted(set(node["options"])):
        long = opt.lstrip("-")
        fish_lines.append(f"complete -c mycelos -n '{cond}' -l '{long}'")

with open(os.environ["MYCELOS_FISH_OUT"], "w") as f:
    f.write("\n".join(fish_lines) + "\n")

print("ok")
PY

    if [ $? -ne 0 ]; then
        log "   (rendering failed — skipping)"
        return 0
    fi

    log "⇥  Tab-completion installed (bash, zsh, fish) — zero runtime cost"
    # FPATH only exists in zsh. Under bash (which installs.sh runs in)
    # ${FPATH:-} dodges 'unbound variable' under `set -u`.
    case ":${FPATH:-}:" in
        *":$zsh_dir:"*) ;;
        *)
            log "   zsh users: add to ~/.zshrc so zsh finds the completion file:"
            log "     fpath=(${zsh_dir//$HOME/\$HOME} \$fpath); autoload -Uz compinit && compinit"
            ;;
    esac
    log "   Reopen your shell to activate. Re-run install.sh to refresh after an update."
}

bring_up() {
    [ "$DRY_RUN" = 1 ] && { log "Dry run: skipping docker compose pull/up"; return; }

    log "⬆️  Pulling latest image..."
    docker compose pull

    log "🚀 Starting containers..."
    docker compose up -d

    log "⏳ Waiting for gateway to become healthy (up to 60s)..."
    local deadline=$(( $(date +%s) + 60 ))
    local port
    port="$(grep '^MYCELOS_PORT=' .env | cut -d= -f2)"
    port="${port:-9100}"
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if curl -fsSL "http://localhost:${port}/api/health" >/dev/null 2>&1; then
            log "✅ Mycelos is running — open http://localhost:${port}"
            return
        fi
        sleep 2
    done
    err "Gateway did not become healthy within 60s. Check 'docker compose logs'."
    exit 3
}

check_prereqs
ensure_data_dir
ensure_env
ensure_compose
install_cli_shortcut
bring_up
install_cli_completion
