#!/usr/bin/env bash
# Mycelos installer — zero-question bootstrap for the two-container deployment.
#
# Flags:
#   --dry-run       Skip `docker compose up`; just create files.
#   --data-dir DIR  Persistent volume path (default ./data).
#
# Exit codes:
#   0  success
#   2  prerequisite missing
#   3  stack did not become healthy within 60s

set -euo pipefail

DRY_RUN=0
DATA_DIR="./data"
COMPOSE_SRC="${MYCELOS_COMPOSE_SRC:-https://raw.githubusercontent.com/mycelos-ai/mycelos/main/docker-compose.yml}"

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --data-dir) DATA_DIR="$2"; shift ;;
        -h|--help)
            sed -n '2,10p' "$0"
            exit 0 ;;
        *) echo "Unknown flag: $1" >&2; exit 2 ;;
    esac
    shift
done

log() { echo "==> $*"; }
err() { echo "!!! $*" >&2; }

check_prereqs() {
    command -v docker >/dev/null 2>&1 \
        || { err "Docker not found. Install from https://docs.docker.com/get-docker/"; exit 2; }
    docker compose version >/dev/null 2>&1 \
        || { err "Docker Compose v2 required ('docker compose', not 'docker-compose')"; exit 2; }
    # curl is only required for remote fetches
    if [ ! -f "$COMPOSE_SRC" ]; then
        command -v curl >/dev/null 2>&1 || { err "curl not found"; exit 2; }
    fi
    command -v python3 >/dev/null 2>&1 || command -v openssl >/dev/null 2>&1 \
        || { err "Need python3 or openssl to generate tokens"; exit 2; }
}

gen_token() {
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
    else
        openssl rand -base64 48 | tr -d '\n' | head -c 43
    fi
}

ensure_data_dir() {
    mkdir -p "$DATA_DIR"
    if [ ! -f "$DATA_DIR/.master_key" ]; then
        log "Generating .master_key in $DATA_DIR"
        gen_token > "$DATA_DIR/.master_key"
        chmod 600 "$DATA_DIR/.master_key"
    else
        log ".master_key already exists — keeping it"
    fi
    # Pre-create the DB file so the proxy's read-only bind-mount has a target.
    # Mycelos auto-initializes the schema on first gateway start.
    touch "$DATA_DIR/mycelos.db"
}

ensure_env() {
    if [ -f .env ]; then
        log ".env exists — keeping it"
        return
    fi
    log "Writing .env with a fresh MYCELOS_PROXY_TOKEN"
    local token
    token="$(gen_token)"
    cat > .env <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MYCELOS_PROXY_TOKEN="$token"
MYCELOS_DATA_DIR="$DATA_DIR"
MYCELOS_PORT=9100
EOF
    chmod 600 .env
}

ensure_compose() {
    if [ -f docker-compose.yml ]; then
        log "docker-compose.yml exists — keeping it"
        return
    fi
    if [ -f "$COMPOSE_SRC" ]; then
        log "Copying $COMPOSE_SRC"
        cp "$COMPOSE_SRC" docker-compose.yml
    else
        log "Fetching docker-compose.yml"
        curl -fsSL "$COMPOSE_SRC" -o docker-compose.yml
    fi
}

bring_up() {
    [ "$DRY_RUN" = 1 ] && { log "Dry run: skipping 'docker compose up'"; return; }

    log "Starting containers..."
    docker compose up -d

    log "Waiting for /api/health (up to 60s)..."
    local deadline=$(( $(date +%s) + 60 ))
    local port
    port="$(grep '^MYCELOS_PORT=' .env | cut -d= -f2)"
    port="${port:-9100}"
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if curl -fsSL "http://localhost:${port}/api/health" >/dev/null 2>&1; then
            log "Healthy. Open http://localhost:${port} to finish setup."
            return
        fi
        sleep 2
    done
    err "Gateway did not become healthy within 60s. Check 'docker compose logs'."
    exit 3
}

check_prereqs
ensure_data_dir
ensure_env
ensure_compose
bring_up
log "Done."
