#Requires -Version 5.1
<#
.SYNOPSIS
  Mycelos installer (Windows / PowerShell).
.PARAMETER DryRun
  Skip 'docker compose up'; just create files.
.PARAMETER DataDir
  Persistent volume path (default .\data).
#>
param(
    [switch]$DryRun,
    [string]$DataDir = ".\data"
)

$ErrorActionPreference = "Stop"
function Write-Log($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Err($msg) { Write-Host "!!! $msg" -ForegroundColor Red }

function New-Token {
    # 32 random bytes → URL-safe base64, ≈ 43 chars
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_')
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Err "Docker Desktop not found. See https://docs.docker.com/desktop/install/windows-install/"
        exit 2
    }
    docker compose version *> $null
    if ($LASTEXITCODE -ne 0) { Write-Err "Docker Compose v2 required"; exit 2 }
}

function Initialize-DataDir {
    if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir | Out-Null }
    $keyPath = Join-Path $DataDir ".master_key"
    if (-not (Test-Path $keyPath)) {
        Write-Log "Generating .master_key in $DataDir"
        New-Token | Set-Content -Path $keyPath -NoNewline -Encoding ASCII
    } else {
        Write-Log ".master_key already exists — keeping it"
    }
    $dbPath = Join-Path $DataDir "mycelos.db"
    if (-not (Test-Path $dbPath)) { New-Item -ItemType File -Path $dbPath | Out-Null }
}

function Initialize-EnvFile {
    if (Test-Path ".env") { Write-Log ".env exists — keeping it"; return }
    Write-Log "Writing .env"
    $token = New-Token
    @"
# Generated by scripts/install.ps1 on $([DateTime]::UtcNow.ToString("o"))
MYCELOS_PROXY_TOKEN=$token
MYCELOS_DATA_DIR=$DataDir
MYCELOS_PORT=9100
"@ | Set-Content -Path ".env" -Encoding UTF8
}

function Initialize-Compose {
    $src = "https://raw.githubusercontent.com/mycelos-ai/mycelos/main/docker-compose.yml"
    if (-not (Test-Path "docker-compose.yml")) {
        Write-Log "Fetching docker-compose.yml"
        Invoke-WebRequest -Uri $src -OutFile "docker-compose.yml"
    }
}

function Start-Stack {
    if ($DryRun) { Write-Log "Dry run: skipping 'docker compose up'"; return }
    Write-Log "Starting containers..."
    docker compose up -d
    $deadline = [DateTime]::UtcNow.AddSeconds(60)
    while ([DateTime]::UtcNow -lt $deadline) {
        try {
            $r = Invoke-WebRequest -Uri "http://localhost:9100/api/health" -UseBasicParsing -TimeoutSec 2
            if ($r.StatusCode -eq 200) {
                Write-Log "Healthy. Open http://localhost:9100 to finish setup."
                return
            }
        } catch { }
        Start-Sleep -Seconds 2
    }
    Write-Err "Gateway did not become healthy in 60s. Check 'docker compose logs'."
    exit 3
}

Assert-Docker
Initialize-DataDir
Initialize-EnvFile
Initialize-Compose
Start-Stack
Write-Log "Done."
