@use-case @agent-template @creator-agent @code-generation @milestone-3
Feature: Agent Code Template and Structure
  As the Creator-Agent
  I want to generate agents with a consistent code structure
  So that all agents follow the same patterns and are maintainable

  Every agent generated by the Creator-Agent follows a standard template.
  The template ensures: proper error handling, progress reporting,
  tool calls through the SDK, and correct input/output contracts.

  Background:
    Given the Creator-Agent is active
    And the user has requested a new agent

  @template @structure
  Scenario: Generated agent follows the standard template
    When the Creator-Agent generates a new email-summary agent
    Then the generated code has this structure:
      | section              | required | description                               |
      | class declaration    | yes      | Class with agent_id, agent_type, capabilities |
      | execute method       | yes      | Takes AgentInput, returns AgentOutput      |
      | try/except wrapper   | yes      | Catches all exceptions, never propagates   |
      | progress calls       | yes      | At least start + finish progress           |
      | run() for tools      | yes      | All external calls via mycelos.sdk.run()    |
      | validate_output      | optional | Self-validation before EvaluatorAgent      |
    And the code imports only from mycelos.sdk and Python stdlib
    And no direct imports of requests, urllib, httpx, or similar

  @template @error-handling
  Scenario: Generated agent handles errors gracefully
    When the Creator-Agent generates an agent
    Then the execute() method wraps all logic in try/except:
      """
      def execute(self, input: AgentInput) -> AgentOutput:
          try:
              # ... agent logic ...
              return AgentOutput(success=True, ...)
          except Exception as e:
              return AgentOutput(success=False, error=str(e), ...)
      """
    And the agent NEVER raises unhandled exceptions
    And errors are returned as AgentOutput with success=False

  @template @progress
  Scenario: Generated agent reports progress
    When a generated agent runs
    Then it calls progress() at minimum:
      | when              | message example                    |
      | at start          | "Starte email-summary..."          |
      | during processing | "Verarbeite Email 3 von 17..."     |
      | at finish         | "Fertig."                          |
    And progress calls are non-blocking (fire and forget)

  @template @sdk-only
  Scenario: Generated agent uses SDK for all external calls
    When the Creator-Agent generates an agent that needs:
      | operation          | correct tool call                    |
      | read emails        | run(tool="email.read", ...)          |
      | call external API  | run(tool="http.get", ...)            |
      | create artifact    | run(tool="artifacts.create", ...)    |
      | use LLM            | run(tool="llm.complete", ...)        |
    Then every external operation goes through run()
    And no direct network calls exist in the generated code
    And the AuditorAgent verifies no unauthorized imports

  @template @auditor-review
  Scenario: AuditorAgent rejects agent with bad patterns
    When the Creator-Agent generates an agent that contains:
      """
      import requests
      response = requests.get("https://api.example.com")
      """
    Then the AuditorAgent flags the code:
      """
      Rejected: Direct HTTP import detected (requests).
      Agents must use run(tool="http.get", ...) for all network access.
      This ensures all requests flow through the Security Layer.
      """
    And the agent is NOT registered
    And the Creator-Agent is asked to fix the code

  @template @deterministic
  Scenario: Deterministic agents don't need LLM tools
    When the Creator-Agent generates a deterministic agent (e.g., PDF parser)
    Then the agent_type is set to "deterministic"
    And the code uses only stdlib tools (subprocess, json, re, etc.)
    And no run(tool="llm.complete") calls are present
    And the agent's cost per execution is documented as "$0.00"

  @template @streaming-agent
  Scenario: Agent with streaming LLM output
    When the Creator-Agent generates an agent that needs LLM streaming
    Then the code uses:
      """
      result = run(tool="llm.complete", args={
          "prompt": "...",
          "model_tier": "haiku",
          "stream": True
      })
      """
    And the streaming response is handled correctly
    And partial results are forwarded via progress() if needed

  @template @tests-generated
  Scenario: Creator-Agent generates tests alongside agent code
    When a new agent is generated
    Then the Creator-Agent also generates test code:
      | test type   | example                                        |
      | happy path  | test_agent_returns_expected_output              |
      | empty input | test_agent_handles_empty_input_gracefully       |
      | error case  | test_agent_handles_tool_failure                 |
      | validation  | test_output_matches_expected_format             |
    And the test file uses the same AgentInput/AgentOutput contracts
    And tests can run without real external services (mocked tools)
